import type { Festival } from "../types.js";

export const festivalsSeed: Festival[] = [
  {
    id: "tomorrowland",
    name: "Tomorrowland",
    country: "Belgium",
    genre: "EDM",
    vibe: "Beach",
    size: "Huge",
    month: 7,
    url: "https://www.tomorrowland.com/",
    image:
      "https://djmag.com/sites/default/files/styles/djm_23_961x540_jpg/public/2023-08/tomorrowland-top-100-festivals_0.jpg",
    lat: 51.091,
    lng: 4.403,
    description: "The most spectacular electronic music festival in the world.",
    featured: true,
  },
  {
    id: "sziget",
    name: "Sziget",
    country: "Hungary",
    genre: "Mixed",
    vibe: "Urban",
    size: "Huge",
    month: 8,
    url: "https://szigetfestival.com/",
    image:
      "https://szigetfestival.com/wp-content/uploads/2024/03/DJI_20240810214150_0325_D-scaled.jpg",
    lat: 47.555,
    lng: 19.046,
    description: "An island of freedom, art and music for hundreds of thousands of people.",
    featured: true,
  },
  {
    id: "untold",
    name: "Untold",
    country: "Romania",
    genre: "EDM",
    vibe: "Urban",
    size: "Huge",
    month: 8,
    url: "https://untold.com/",
    image: "https://viacluj.tv/wp-content/uploads/2022/08/untold-3.jpg",
    lat: 46.77,
    lng: 23.59,
    description: "Magic, lights and energy in a massive EDM and pop festival.",
    featured: true,
  },
  {
    id: "boom",
    name: "Boom Festival",
    country: "Portugal",
    genre: "Techno",
    vibe: "Nature",
    size: "Medium",
    month: 7,
    url: "https://boomfestival.org/",
    image: "https://tribalreunion.com/wpfiles/wp-content/uploads/2020/05/Boom-festival-6608.jpg",
    lat: 39.61,
    lng: -7.49,
    description: "An alternative experience blending techno, art and nature.",
    featured: true,
  },
  {
    id: "primavera-sound",
    name: "Primavera Sound",
    country: "Spain",
    genre: "Indie",
    vibe: "Urban",
    size: "Medium",
    month: 5,
    url: "https://www.primaverasound.com/",
    image:
      "https://static01.nyt.com/images/2014/06/01/arts/music/20140601PRIMA-slide-LEBV/20140601PRIMA-slide-LEBV-superJumbo.jpg",
    lat: 41.39,
    lng: 2.17,
    description: "An urban mix of indie, electronic music and contemporary art.",
    featured: true,
  },
  {
    id: "electric-castle",
    name: "Electric Castle",
    country: "Romania",
    genre: "EDM",
    vibe: "Castle",
    size: "Medium",
    month: 7,
    url: "https://electriccastle.ro/",
    image:
      "https://media.electriccastle.ro/stories/article/ECMag_Choosing_the_right_festival_thumbnail.jpg",
    lat: 46.9,
    lng: 23.74,
    description: "Music, technology and a magical atmosphere inside a Transylvanian castle.",
    featured: true,
  },
  {
    id: "dimensions",
    name: "Dimensions",
    country: "Croatia",
    genre: "Techno",
    vibe: "Beach",
    size: "Medium",
    month: 6,
    url: "https://www.dimensionsfestival.com/",
    image:
      "https://www.visit-croatia.co.uk/wp-content/uploads/2022/02/210904_DIMENSIONS_2021_JakeDavis_@jakephilipdaviis_@khromacollective-3537.jpg",
    lat: 44.87,
    lng: 13.85,
    description: "Underground techno by the sea, set in a stunning industrial backdrop.",
    featured: true,
  },
  {
    id: "jazz-in-the-park",
    name: "Jazz in the Park",
    country: "Romania",
    genre: "Jazz",
    vibe: "Nature",
    size: "Medium",
    month: 7,
    url: "https://www.jazzinthepark.ro/",
    image: "https://clujwebstory.ro/images/2024/06/Jazz-in-the-Park-Competition-2.jpg",
    lat: 46.77,
    lng: 23.6,
    description: "Jazz, chill vibes and community in a park full of atmosphere and relaxation.",
    featured: true,
  },
  {
    id: "nos-alive",
    name: "NOS Alive",
    country: "Portugal",
    genre: "Rock",
    vibe: "Urban",
    size: "Medium",
    month: 9,
    url: "https://www.nosalive.com/",
    image:
      "https://znaki.fm/static/content/thumbs/1600x900/f/f9/qddk2j---c16x9x50px50p--ae5f52feb38a61495122075e9dda7f9f.jpeg",
    lat: 38.72,
    lng: -9.3,
    description: "A riverside stage lineup mixing rock headliners with pop and indie acts.",
    featured: false,
  },
  {
    id: "exit",
    name: "EXIT",
    country: "Serbia",
    genre: "EDM",
    vibe: "Castle",
    size: "Huge",
    month: 9,
    url: "https://www.exitfest.org/",
    image: "https://www.clashmusic.com/wp-content/uploads/2024/12/exit-festival.jpg",
    lat: 45.2671,
    lng: 19.8335,
    description: "Held inside an 18th-century fortress overlooking the Danube.",
    featured: false,
  },
  {
    id: "opener",
    name: "Open'er",
    country: "Poland",
    genre: "Pop",
    vibe: "Beach",
    size: "Huge",
    month: 8,
    url: "https://opener.pl/",
    image:
      "https://rytmy.pl/wp-content/uploads/bfi_thumb/Opener_1-e1554471597576-oa8vhujhxl9t22qno95na5fo516hgsqs20d494fxio.jpg",
    lat: 54.5189,
    lng: 18.5305,
    description: "A Baltic coast festival known for booking huge global headliners.",
    featured: false,
  },
  {
    id: "rock-en-seine",
    name: "Rock en Seine",
    country: "France",
    genre: "Rock",
    vibe: "Urban",
    size: "Medium",
    month: 6,
    url: "https://www.rockenseine.com/",
    image:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/25/6e/11/3d/festival-rock-en-seine.jpg",
    lat: 48.8459,
    lng: 2.2148,
    description: "A rock and alternative lineup in a park on the edge of Paris.",
    featured: false,
  },
  {
    id: "dekmantel",
    name: "Dekmantel",
    country: "Netherlands",
    genre: "Techno",
    vibe: "Nature",
    size: "Medium",
    month: 8,
    url: "https://www.dekmantelfestival.com/",
    image:
      "https://mixmag.net/assets/uploads/images/_fullX2/Atmosphere-2-Dekmantel-Ten-please-credit-Tim-Buiting.jpg",
    lat: 52.3676,
    lng: 4.9041,
    description: "A woodland techno and house festival curated by DJs, for DJs.",
    featured: false,
  },
  {
    id: "mysteryland",
    name: "Mysteryland",
    country: "Netherlands",
    genre: "EDM",
    vibe: "Nature",
    size: "Medium",
    month: 8,
    url: "https://www.mysteryland.nl/",
    image: "https://visithaarlemmermeer.nl/sites/default/files/visual_image_teaser/Mysteryland2.jpg",
    lat: 52.3,
    lng: 4.68,
    description: "One of the world's oldest electronic music festivals, built around bold art installations.",
    featured: false,
  },
  {
    id: "balaton-sound",
    name: "Balaton Sound",
    country: "Hungary",
    genre: "EDM",
    vibe: "Beach",
    size: "Huge",
    month: 8,
    url: "https://www.balatonsound.com/",
    image: "https://i.ytimg.com/vi/TtWnvH2oMfA/maxresdefault.jpg",
    lat: 46.885,
    lng: 17.95,
    description: "Beats and beach days on the shore of Lake Balaton.",
    featured: false,
  },
  {
    id: "les-eurockeennes",
    name: "Les Eurockéennes",
    country: "France",
    genre: "Rock",
    vibe: "Nature",
    size: "Medium",
    month: 8,
    url: "https://www.eurockeennes.fr/",
    image:
      "https://www.eurockeennes.fr/wp-content/uploads/2023/12/eurocks2019-ambiance-bricerobert-41-scaled.jpg",
    lat: 47.6379,
    lng: 6.8629,
    description: "A rock, indie and hip-hop festival on a lakeside peninsula.",
    featured: false,
  },
  {
    id: "sunscape",
    name: "Sunscape",
    country: "Croatia",
    genre: "Techno",
    vibe: "Beach",
    size: "Intimate",
    month: 6,
    url: "https://sunscape.live/",
    image: "https://www.noa-zrce.com/data/public/eventi/sunscape-sa-by-edge-84.jpeg",
    lat: 44.5657,
    lng: 14.9298,
    description: "Sunrise sets on Zrće Beach for a smaller, close-knit crowd.",
    featured: false,
  },
  {
    id: "fusion",
    name: "Fusion",
    country: "Germany",
    genre: "Rock",
    vibe: "Mountain",
    size: "Intimate",
    month: 7,
    url: "https://www.fusion-festival.de/",
    image: "https://undergroundsound.eu/wp-content/uploads/2024/01/Fusion-6-by-Montecruz-Foto.jpg",
    lat: 53.3167,
    lng: 12.85,
    description: "A non-commercial festival on a former airfield, run entirely by volunteers.",
    featured: false,
  },
  {
    id: "meadows",
    name: "Meadows in the Mountains",
    country: "Bulgaria",
    genre: "Indie",
    vibe: "Mountain",
    size: "Intimate",
    month: 6,
    url: "https://meadowsinthomountains.com/",
    image:
      "https://i0.wp.com/liveforlivemusic.com/wp-content/uploads/2018/08/the-meadows-day-one-Stages-and-people-9.15.17-chad-anderson-photography-8479-1200x630.jpg",
    lat: 41.9,
    lng: 24.75,
    description: "A boutique festival tucked into the Rhodope mountains.",
    featured: false,
  },
  {
    id: "love-international",
    name: "Love International",
    country: "Croatia",
    genre: "Indie",
    vibe: "Beach",
    size: "Intimate",
    month: 7,
    url: "https://loveinternationalfestival.com/",
    image: "https://media.timeout.com/images/103073017/image.jpg",
    lat: 43.798,
    lng: 15.633,
    description: "A boutique beach festival built around an open-air club stage.",
    featured: false,
  },
];
